package in.prabhupaints.stock;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;import android.print.PrintManager;import android.util.AtomicFile;import org.json.*;import java.io.*;
public class MainActivity extends Activity {
 WebView web; String pending=""; final String ORIGIN="https://app.prabhupaints.local/";
 public void onCreate(Bundle b){super.onCreate(b);web=new WebView(this);web.setBackgroundColor(0xfff5f0e7);web.setFitsSystemWindows(true);setContentView(web);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.addJavascriptInterface(new Bridge(),"Shop");web.setWebChromeClient(new WebChromeClient());web.setWebViewClient(new WebViewClient(){
 public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return !r.getUrl().toString().startsWith(ORIGIN);}
 public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){try {String url=r.getUrl().toString();if(!url.startsWith(ORIGIN))return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));String p=Uri.parse(url).getPath().substring(1);if(p.contains(".."))throw new IOException();if(p.isEmpty())p="index.html";InputStream in=p.startsWith("media/")?new FileInputStream(new File(getFilesDir(),p)):getAssets().open(p);String mime=p.endsWith(".js")?"application/javascript":p.endsWith(".css")?"text/css":p.endsWith(".json")?"application/json":p.endsWith(".jpg")?"image/jpeg":p.endsWith(".png")?"image/png":p.endsWith(".webp")?"image/webp":p.endsWith(".mp4")?"video/mp4":"text/html";return new WebResourceResponse(mime,"UTF-8",in);}catch(Exception e){return new WebResourceResponse("text/plain","UTF-8",new ByteArrayInputStream(new byte[0]));}}
 });web.loadUrl(ORIGIN);}
 String read(InputStream in,int max)throws IOException {ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){out.write(b,0,n);if(out.size()>max)throw new IOException("File too large");}in.close();return out.toString("UTF-8");}
 void js(String s){runOnUiThread(()->web.evaluateJavascript(s,null));}
 void notifyUser(String s){runOnUiThread(()->new AlertDialog.Builder(this).setMessage(s).setPositiveButton("OK",null).show());}
 class Bridge {
 @JavascriptInterface public boolean configureCloud(String address){try{Uri u=Uri.parse(address);if(!"https".equals(u.getScheme())||u.getHost()==null||!u.getHost().endsWith(".up.railway.app")||u.getUserInfo()!=null||u.getPort()!=-1||(u.getPath()!=null&&!u.getPath().isEmpty())||u.getQuery()!=null||u.getFragment()!=null)return false;android.content.SharedPreferences p=getSharedPreferences("cloud",MODE_PRIVATE);if(!address.equals(p.getString("origin","")))p.edit().putString("origin",address).remove("token").commit();return true;}catch(Exception e){return false;}}
 @JavascriptInterface public void cloudRequest(String id,String path,String method,String body){new Thread(()->{int status=500;String result="{\"error\":\"Cloud connection failed\"}";try{if(!path.equals("/api/shop")&&!path.equals("/api/login")&&!path.equals("/api/logout"))throw new IOException("Unsupported request");if(!method.equals("GET")&&!method.equals("POST"))throw new IOException("Unsupported method");android.content.SharedPreferences p=getSharedPreferences("cloud",MODE_PRIVATE);String base=p.getString("origin","");if(base.isEmpty())throw new IOException("Enter your cloud address first");java.net.HttpURLConnection c=(java.net.HttpURLConnection)new java.net.URL(base+path).openConnection();c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(25000);c.setRequestMethod(method);c.setRequestProperty("Origin",base);c.setRequestProperty("X-Shop-Request","1");c.setRequestProperty("X-Native-Client","1");c.setRequestProperty("Content-Type","application/json");String token=p.getString("token","");if(!token.isEmpty())c.setRequestProperty("Authorization","Bearer "+token);if(method.equals("POST")){c.setDoOutput(true);try(OutputStream o=c.getOutputStream()){o.write(body.getBytes("UTF-8"));}}status=c.getResponseCode();InputStream input=status<400?c.getInputStream():c.getErrorStream();result=input==null?"{}":read(input,10000000);if(path.equals("/api/login")&&status==200){JSONObject j=new JSONObject(result);p.edit().putString("token",j.getString("token")).commit();j.remove("token");result=j.toString();}if(path.equals("/api/logout"))p.edit().remove("token").commit();c.disconnect();}catch(Exception e){status=0;try{result=new JSONObject().put("error",e.getMessage()).toString();}catch(Exception ignored){}}js("cloudResponse("+JSONObject.quote(id)+","+status+","+JSONObject.quote(result)+")");}).start();}
 @JavascriptInterface public void exportText(String content,String filename,String mime){pending=content;runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/csv");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,filename);startActivityForResult(i,44);});}

 @JavascriptInterface public String load(){try{return read(new AtomicFile(new File(getFilesDir(),"stock-state.json")).openRead(),10000000);}catch(Exception e){return "";}}
 @JavascriptInterface public boolean save(String json){AtomicFile f=new AtomicFile(new File(getFilesDir(),"stock-state.json"));FileOutputStream o=null;try {new JSONObject(json);o=f.startWrite();o.write(json.getBytes("UTF-8"));f.finishWrite(o);return true;}catch(Exception e){if(o!=null)f.failWrite(o);return false;}}
 @JavascriptInterface public void print(){runOnUiThread(()->((PrintManager)getSystemService(PRINT_SERVICE)).print("Prabhu Paints",web.createPrintDocumentAdapter("Prabhu Paints Invoice"),null));}
 @JavascriptInterface public void exportBackup(String s){pending=s;runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"Prabhu-Paints-Backup-"+System.currentTimeMillis()+".json");startActivityForResult(i,41);});}
 @JavascriptInterface public void importBackup(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,42);});}
 @JavascriptInterface public void addMedia(){runOnUiThread(()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.putExtra(Intent.EXTRA_MIME_TYPES,new String[]{"image/jpeg","image/png","image/webp","video/mp4"});i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,43);});}
 }
 protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null)return;try{Uri u=data.getData();if(req==41||req==44){try(OutputStream o=getContentResolver().openOutputStream(u)){o.write(pending.getBytes("UTF-8"));}pending="";notifyUser(req==41?"Backup saved. Photos and videos are not included; keep the original media files.":"CSV exported.");}else if(req==42){String s=read(getContentResolver().openInputStream(u),10000000);js("restoreBackup("+JSONObject.quote(s)+")");}else if(req==43){String type=getContentResolver().getType(u);String ext="image/jpeg".equals(type)?"jpg":"image/png".equals(type)?"png":"image/webp".equals(type)?"webp":"video/mp4".equals(type)?"mp4":null;if(ext==null)throw new IOException("Choose JPG, PNG, WebP or MP4");File dir=new File(getFilesDir(),"media");dir.mkdirs();String name=System.currentTimeMillis()+"."+ext;File dest=new File(dir,name);try(InputStream in=getContentResolver().openInputStream(u);OutputStream out=new FileOutputStream(dest)){byte[] b=new byte[8192];int n,total=0;while((n=in.read(b))!=-1){total+=n;if(total>100000000)throw new IOException("Limit is 100 MB");out.write(b,0,n);}}catch(Exception e){dest.delete();throw e;}js("mediaAdded("+JSONObject.quote("media/"+name)+","+JSONObject.quote(type)+")");}}catch(Exception e){notifyUser("Could not complete: "+e.getMessage());}}
 public void onBackPressed(){js("go('home')");}
}
