plugins { id 'com.android.application' }

android {
    namespace 'in.prabhupaints.vksnative'
    compileSdk 35

    defaultConfig {
        applicationId 'in.prabhupaints.vksnative'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '2.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['META-INF/NOTICE.md','META-INF/LICENSE.md']
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.room:room-runtime:2.7.2'
    annotationProcessor 'androidx.room:room-compiler:2.7.2'
    implementation 'androidx.work:work-runtime:2.10.1'
    implementation 'androidx.documentfile:documentfile:1.1.0'
}
